### ISSUE TITLE
Delete unreferenced elements - 0 records

### ISSUE THREAD

**Issue by andihuber** [derhansen/sf_tv2fluidge#101]
Hello,

i get 0 records as deleted when i "Delete unreferenced records", but there are many of them.

I installed the devlog extension and this is what i get when i click the button:

xec_UPDATEquery
caller	TYPO3\CMS\Core\Database\DatabaseConnection::exec_UPDATEquery

ERROR	You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

lastBuiltQuery	UPDATE tt_content SET deleted='1' WHERE uid IN ()

debug_backtrace	TYPO3\CMS\Extbase\Core\ModuleRunner->callModule#38 // TYPO3\CMS\Extbase\Core\Bootstrap->run#67 // TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#184 // TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest#195 // TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch#33 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest#69 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod#157 // call_user_func_array#286 // Tx_SfTv2fluidge_Controller_Tv2fluidgeController->deleteUnreferencedElementsAction# // Tx_SfTv2fluidge_Service_UnreferencedElementHelper->markDeletedUnreferencedElementsRecords#175 // Tx_SfTv2fluidge_Service_UnreferencedElementHelper->markDeleted#72 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_UPDATEquery#118 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#245

Typo3 Version is 6.2.9

Do you have an idea what causes this issue?

Thank you, best regards,
Andreas Huber

**Comment by derhansen** [comment]
Hello Andreas,

I tried to reproduce your problem with no luck. My test TYPO3 installation with the latest TemplaVoila version for TYPO3 6.2 works as expected.

You could try to debug the function markDeletedUnreferencedElementsRecords and then digg into $this->getUnreferencedElementsRecords($allReferencedElementsArr); to see, why no record UIDs are returned.

Best regards
Torben

**Comment by derhansen** [comment]
Closing - No feedback
