### ISSUE TITLE
References not converted

### ISSUE THREAD

**Issue by mlueft** [derhansen/sf_tv2fluidge#103]
I have TV-FCEs on my page. They contains local content and references.

The tx_templavoila_flex looks like this:
for page 2:
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="content">
                    <value index="vDEF">1200</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```
for content 1200
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="maincontent">
                    <value index="vDEF">1202,2307,1603,3210,2508</value>
                </field>
                <field index="rightsidebar">
                    <value index="vDEF">3183,1675,1500,2305</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```
After migrating the website those references are missing.

"Convert references" says "0 records has been converted."

My system:
Typo3:  4.7.1
Templavoila: 1.8.0
tv2fluidge 0.4.0

Any idea what is going on here? Thanksful for any help.

regards,

michael

**Comment by derhansen** [comment]
Hi Michael,

I'm sorry but I can't really help here except from suggesting to manually debug the whole `convertReferenceElements()` method. I think, that `getContentArrayFromFlexform()` returns nothing, but this is only a guess from me.

After the conversion, you should at least have an "Insert Record" element for each TV Reference (independent of the type - content element/TV FCE). TV FCE must be converted manually to Grid Elements in order to assign content elements to Grid columns.

I hope this helps in some way.

Best regards
Torben

**Comment by mlueft** [comment]
Thanks i will try my best and give Feedback.

Regards
Am 13.06.2016 21:51 schrieb "Torben Hansen" <notifications@github.com>:

**Comment by mlueft** [comment]
Found it!

"Template for subpages" definition in root page properties was missing.

**Comment by derhansen** [comment]
Thanks for your feedback and great it now works for you!

**Comment by mlueft** [comment]
it's nearly working.
After migration, I have the strange failure.

If the language of the GE is "default", I see them in the Backend, but not
in the frontend.
If the language if the GE is "all", I see them in the frontend, but not in
the backend.

Do you have any idea? I have no idea, what's going on here.
If I create a new GE, it's working.

regards,

michael

On Thu, Jun 16, 2016 at 8:57 AM, Torben Hansen <notifications@github.com>
wrote:

> Thanks for your feedback and great it now works for you!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/derhansen/sf_tv2fluidge/issues/103#issuecomment-226403458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxelz6qG6yO-1cUREU9ajPh3sgVl8SUks5qMPPpgaJpZM4Iz3YS>
> .
>



-- 
http://www.kineticarm.com - your place to play online games
<http://www.kineticarm.com>
http://www.lueftenegger.at

**Comment by derhansen** [comment]
Do you mean, that GE with language "all" are not visible in the frontend or backend? If frontend, please check the TYPO3 language settings (e.g. `sys_language_overlay` and `sys_language_mode`)
