### ISSUE TITLE
[TASK] Add TYPO3 7.6 support

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_tv2fluidge#107]
Add TYPO3 7.6 support, when a working version of TemplaVoila for TYPO3 7.6 is available

**Comment by CrashTestFetus** [comment]
https://www.templavoila.support/

**Comment by Outdoorsman** [comment]
Most people where needed to still be using `templavoila` in TYPO3 7.6 or 8.7 have migrated to `templavoilaplus`. This presents a real problem though because then there is not path at all to migrate content to `fluidtemplate` or `gridelements`.

**Comment by derhansen** [comment]
Sorry, but I will not have time to create a version of sf_tv2fluidge, which is compatible with templavoilaplus (see #112)

**Comment by Outdoorsman** [comment]
> Most people who needed to still be using templavoila in TYPO3 7.6 or 8.7 have migrated to templavoilaplus. This presents a real problem though because then there is not path at all to migrate content to fluidtemplate or gridelements.

Oops... I take that back. I'm migrating some websites now and see that `templavoila` release five versions that supported TYPO3 7.6.

**Comment by Outdoorsman** [comment]
I understand about not having enough time for adding `templavoilaplus` functionality. I'd help but am not at that level of a programmer yet.

**Comment by derhansen** [comment]
I tried the TER version of `templavoila` with TYPO3 7.6 but with no success. 

Please see my note in #112 - maybe Gernot Ploiner has a migrator which supports `templavoilaplus`
