### ISSUE TITLE
delete unreferenced elements, maybe allow optional to set colPos=255 and hidden or similiar

### ISSUE THREAD

**Issue by AndreasA** [derhansen/sf_tv2fluidge#76]
Regarding unreferenced CE though they are not visible, you can still "restore" them, so it might also be an idea to allow instead of deleting to set colPos=255 and maybe also hidden=1 (which most likely will not be used) and that way a backend user would also be able to "restore" the element by using the list module.

**Comment by hannesbochmann** [comment]
I think -1 is not valid. The field is an unsigned integer in the database. Therefore this leads to having all datasets set to colPos 0 which means they are main column.
This needs to be fixed.
