### ISSUE TITLE
Respect the TemplaVoila template inheritance mechanism

### ISSUE THREAD

**Issue by thokel** [derhansen/sf_tv2fluidge#93]
Hi,

first of all I want to thank you for this great extension! I think the inheritance of templates in TemplaVoila differs from the inheritance mechanism with backend layouts. As far as I can see this is not respected in the migration process by now (step "Migrate content").

Example: There are three pages A, B and C, with A being the parent of B, and B being the parent of C. In the page properties of A a template for the site itself (e.g. template 1) and its subpages (e.g. template 2) is defined. In the page properties of B only a template for the site itself is defined (e.g. template 3). If the page properties of C don't define other template records this leads to the following rendering of pages:

| Site | rendered with TV | rendered with fluid templates |
| --- | --- | --- |
| A | template 1 | template 1 |
| -- B | template 3 | template 3 |
| -- -- C | template 3 | template 2 |

As you can see the rendering of site C is different. I'm not sure if this is a bug of this extension, or a bug of TemplaVoila. Nevertheless, it causes a wrong rendering in the frontend after the templates are migrated (at least for me).

I was able to fix this by adding the ID of the backend layout for a single site template to the database field backend_layout_next_level. In case of site B this means that the ID of the backend layout for template 3 is assigned to the backend_layout and backend_layout_next_level fields in the database. This leads to a correct rendering of page C. If you wish I can create a pull request.

Cheers,
Thomas

**Comment by derhansen** [comment]
Hi Thomas,

thank you for your feedback. I will check this in my demo TYPO3 installations and come back with feedback soon.

Torben

**Comment by derhansen** [comment]
I created all pages and templates in my demo TYPO3 installation and was surprised, that TemplaVoila behaves as it does. Actually I would expect, that "template2" should be rendered on page C as it does not get overridden on page B. Strange I never stumbled across this problem during the many years I used TemplaVoila.

I think the conversion process works as it should and Fluidtemplate does the correct inheritance of the templates. 

Maybe you could get in contact with the TemplaVoila team and check, if the template inheritance you described contains a bug or if this is intended behaviour.

**Comment by thokel** [comment]
Hi Torben,

I agree that the inheritance of templates in TemplaVoila seems to be wrong. Therefore I was not sure if this is the right place to post this problem. I will get in contact with the TemplaVoila team and come back with feedback!

Thomas

**Comment by thokel** [comment]
Hi Torben,

I have submitted an issue on forge but nobody replied yet (https://forge.typo3.org/issues/66134).

I will provide a pull request with a solution that worked for me. It's up to you to accept or reject it :) But I think the extension's manual should give a hint to the inheritance problem.

Thomas

**Comment by derhansen** [comment]
Closed with #115
