### ISSUE TITLE
Migration to fluidtypo3

### ISSUE THREAD

**Issue by mitrovicsinisaa** [derhansen/sf_tv2fluidge#97]
Hello,

Thanks for great extension :)
One feature you can add is migration to fluidtypo3 also. 
Some TemplaVoila FCE are more like content elements than Grid elements.

Best regards,
Sinisa Mitrovic

**Comment by derhansen** [comment]
Hi, thanks for your feedback. I also had this idea but dropped it, since I don't have time for that feature.

Best regards
Torben
